const path = require('path')
module.exports = {
	mode:'production',
	entry:{
		index:'./src/index.js'
	},
	module:{
		rules:[
			{
				test:/\.js$/,
				use:[
					{
						loader:path.resolve(__dirname,'src/loader/p-loader.js'),
						options:{
							name:'loader'
						}
					},
					{
						loader:path.resolve(__dirname,'src/loader/p-loader1.js'),
						options:{
							name:'loader1'
						}
					}
				]
			}
		]
	},
	output:{
		path:path.resolve(__dirname,'dist'),
		filename:'[name].bundle.js'
	}
}